version: '3'
services:
  back:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: back
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db1:5432/default_db
      - SPRING_DATASOURCE_USERNAME=gen_user
      - SPRING_DATASOURCE_PASSWORD=w!RBFLUbuBWW2-
    ports:
      - "8081:8081"
    depends_on:
      - db1

  db1:
    image: postgres:14-alpine
    container_name: db1
    restart: always
    build:
      context: .
      dockerfile: ./DockerfileDB

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres #gen_user
      POSTGRES_PASSWORD: 123 #w!RBFLUbuBWW2-
      POSTGRES_DB: test-docker #default_db

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
