version: '3'
services:
  back:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: back
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Common-Food
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    ports:
      - "8081:8081"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: db
    restart: always
    build:
      context: .
      dockerfile: ./DockerfileDB

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: Common-Food

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
